# Generated by Django 3.1.13 on 2021-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_vpnclient_ip_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='private_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='public_key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
